name: docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and push docker containers to ghcr.io 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR.io (GH's Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker GitHub release (for aspera client)
        id: docker_build_aspera
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.aspera
          push: true
          tags: |
            ghcr.io/umccr/aspera:latest
            ghcr.io/umccr/aspera:dev-${{ github.run_number }}
# Might not be needed in the near future?: https://github.com/EbiEga/ega-cryptor/tree/master ... they introduced .github/workflows 1 month ago...
      - name: Docker GitHub release (for ega-crypt)
        id: docker_build_ega_crypt
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.egacrypt
          push: true
          tags: |
            ghcr.io/umccr/egacrypt:latest
            ghcr.io/umccr/egacrypt:dev-${{ github.run_number }}
